export const fonts = {
  jalnan: 'Jalnan2',
  gmarketBold: 'GmarketSansTTFBold',
  gmarketMedium: 'GmarketSansTTFMedium',
  gmarketLight: 'GmarketSansTTFLight',
  pretendardBlack: 'Pretendard-Black',
  pretendardExtraBold: 'Pretendard-ExtraBold',
  pretendardBold: 'Pretendard-Bold',
  pretendardSemiBold: 'Pretendard-SemiBold',
  pretendardMedium: 'Pretendard-Medium',
  pretendardRegular: 'Pretendard-Regular',
  pretendardLight: 'Pretendard-Light',
  pretendardExtraLight: 'Pretendard-ExtraLight',
  pretendardThin: 'Pretendard-Thin',
} as const;
